// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package administration.actions;

import com.mendix.core.Core;
import com.mendix.core.objectmanagement.member.MendixHashString;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

import administration.proxies.PasswordHistory;

public class RecordPasswordHistory extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __AccountWithNewPassword;
	private administration.proxies.Account AccountWithNewPassword;

	public RecordPasswordHistory(IContext context, IMendixObject AccountWithNewPassword)
	{
		super(context);
		this.__AccountWithNewPassword = AccountWithNewPassword;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.AccountWithNewPassword = __AccountWithNewPassword == null ? null : administration.proxies.Account.initialize(getContext(), __AccountWithNewPassword);

		// BEGIN USER CODE
		
		MendixHashString passwordAttribute = (MendixHashString) this.__AccountWithNewPassword.getMember(getContext(), "Password");
		String hashedPassword = passwordAttribute.getValue(getContext());
		
		IMendixObject passwordHist = Core.instantiate(getContext(), PasswordHistory.entityName);
		passwordHist.setValue(getContext(), PasswordHistory.MemberNames.PasswordHash.toString(), hashedPassword);
		passwordHist.setValue(getContext(), PasswordHistory.MemberNames.PasswordHistory_Account.toString(), this.__AccountWithNewPassword.getId());
		Core.commit(getContext(), passwordHist);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RecordPasswordHistory";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
